/*
 * generated by Xtext 2.30.0
 */
package de.tud.st.featurelang.ide;


/**
 * Use this class to register ide components.
 */
public class FeatureLangIdeModule extends AbstractFeatureLangIdeModule {
}
