/**
 * generated by Xtext 2.32.0
 */
package de.tud.st.featurelang.featureLang.impl;

import de.tud.st.featurelang.featureLang.CreationStatement;
import de.tud.st.featurelang.featureLang.FeatureLangPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Creation Statement</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link de.tud.st.featurelang.featureLang.impl.CreationStatementImpl#getClassElement <em>Class Element</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CreationStatementImpl extends StatementImpl implements CreationStatement
{
  /**
   * The cached value of the '{@link #getClassElement() <em>Class Element</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getClassElement()
   * @generated
   * @ordered
   */
  protected de.tud.st.featurelang.featureLang.Class classElement;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CreationStatementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FeatureLangPackage.Literals.CREATION_STATEMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public de.tud.st.featurelang.featureLang.Class getClassElement()
  {
    return classElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetClassElement(de.tud.st.featurelang.featureLang.Class newClassElement, NotificationChain msgs)
  {
    de.tud.st.featurelang.featureLang.Class oldClassElement = classElement;
    classElement = newClassElement;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, FeatureLangPackage.CREATION_STATEMENT__CLASS_ELEMENT, oldClassElement, newClassElement);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setClassElement(de.tud.st.featurelang.featureLang.Class newClassElement)
  {
    if (newClassElement != classElement)
    {
      NotificationChain msgs = null;
      if (classElement != null)
        msgs = ((InternalEObject)classElement).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - FeatureLangPackage.CREATION_STATEMENT__CLASS_ELEMENT, null, msgs);
      if (newClassElement != null)
        msgs = ((InternalEObject)newClassElement).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - FeatureLangPackage.CREATION_STATEMENT__CLASS_ELEMENT, null, msgs);
      msgs = basicSetClassElement(newClassElement, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FeatureLangPackage.CREATION_STATEMENT__CLASS_ELEMENT, newClassElement, newClassElement));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case FeatureLangPackage.CREATION_STATEMENT__CLASS_ELEMENT:
        return basicSetClassElement(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case FeatureLangPackage.CREATION_STATEMENT__CLASS_ELEMENT:
        return getClassElement();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case FeatureLangPackage.CREATION_STATEMENT__CLASS_ELEMENT:
        setClassElement((de.tud.st.featurelang.featureLang.Class)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case FeatureLangPackage.CREATION_STATEMENT__CLASS_ELEMENT:
        setClassElement((de.tud.st.featurelang.featureLang.Class)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case FeatureLangPackage.CREATION_STATEMENT__CLASS_ELEMENT:
        return classElement != null;
    }
    return super.eIsSet(featureID);
  }

} //CreationStatementImpl
