/**
 * generated by Xtext 2.32.0
 */
package de.tud.st.featurelang.featureLang.impl;

import de.tud.st.featurelang.featureLang.CreateInheritance;
import de.tud.st.featurelang.featureLang.EditInheritance;
import de.tud.st.featurelang.featureLang.FeatureLangPackage;
import de.tud.st.featurelang.featureLang.InheritanceAction;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Inheritance Action</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link de.tud.st.featurelang.featureLang.impl.InheritanceActionImpl#getCreate <em>Create</em>}</li>
 *   <li>{@link de.tud.st.featurelang.featureLang.impl.InheritanceActionImpl#getEdit <em>Edit</em>}</li>
 * </ul>
 *
 * @generated
 */
public class InheritanceActionImpl extends MinimalEObjectImpl.Container implements InheritanceAction
{
  /**
   * The cached value of the '{@link #getCreate() <em>Create</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCreate()
   * @generated
   * @ordered
   */
  protected CreateInheritance create;

  /**
   * The cached value of the '{@link #getEdit() <em>Edit</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEdit()
   * @generated
   * @ordered
   */
  protected EditInheritance edit;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InheritanceActionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FeatureLangPackage.Literals.INHERITANCE_ACTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CreateInheritance getCreate()
  {
    return create;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCreate(CreateInheritance newCreate, NotificationChain msgs)
  {
    CreateInheritance oldCreate = create;
    create = newCreate;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, FeatureLangPackage.INHERITANCE_ACTION__CREATE, oldCreate, newCreate);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCreate(CreateInheritance newCreate)
  {
    if (newCreate != create)
    {
      NotificationChain msgs = null;
      if (create != null)
        msgs = ((InternalEObject)create).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - FeatureLangPackage.INHERITANCE_ACTION__CREATE, null, msgs);
      if (newCreate != null)
        msgs = ((InternalEObject)newCreate).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - FeatureLangPackage.INHERITANCE_ACTION__CREATE, null, msgs);
      msgs = basicSetCreate(newCreate, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FeatureLangPackage.INHERITANCE_ACTION__CREATE, newCreate, newCreate));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EditInheritance getEdit()
  {
    return edit;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetEdit(EditInheritance newEdit, NotificationChain msgs)
  {
    EditInheritance oldEdit = edit;
    edit = newEdit;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, FeatureLangPackage.INHERITANCE_ACTION__EDIT, oldEdit, newEdit);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEdit(EditInheritance newEdit)
  {
    if (newEdit != edit)
    {
      NotificationChain msgs = null;
      if (edit != null)
        msgs = ((InternalEObject)edit).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - FeatureLangPackage.INHERITANCE_ACTION__EDIT, null, msgs);
      if (newEdit != null)
        msgs = ((InternalEObject)newEdit).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - FeatureLangPackage.INHERITANCE_ACTION__EDIT, null, msgs);
      msgs = basicSetEdit(newEdit, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FeatureLangPackage.INHERITANCE_ACTION__EDIT, newEdit, newEdit));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case FeatureLangPackage.INHERITANCE_ACTION__CREATE:
        return basicSetCreate(null, msgs);
      case FeatureLangPackage.INHERITANCE_ACTION__EDIT:
        return basicSetEdit(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case FeatureLangPackage.INHERITANCE_ACTION__CREATE:
        return getCreate();
      case FeatureLangPackage.INHERITANCE_ACTION__EDIT:
        return getEdit();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case FeatureLangPackage.INHERITANCE_ACTION__CREATE:
        setCreate((CreateInheritance)newValue);
        return;
      case FeatureLangPackage.INHERITANCE_ACTION__EDIT:
        setEdit((EditInheritance)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case FeatureLangPackage.INHERITANCE_ACTION__CREATE:
        setCreate((CreateInheritance)null);
        return;
      case FeatureLangPackage.INHERITANCE_ACTION__EDIT:
        setEdit((EditInheritance)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case FeatureLangPackage.INHERITANCE_ACTION__CREATE:
        return create != null;
      case FeatureLangPackage.INHERITANCE_ACTION__EDIT:
        return edit != null;
    }
    return super.eIsSet(featureID);
  }

} //InheritanceActionImpl
