/*
 * generated by Xtext 2.30.0
 */
package de.tud.st.featurelang;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class FeatureLangRuntimeModule extends AbstractFeatureLangRuntimeModule {
}
