/*
 * generated by Xtext 2.30.0
 */
package de.tud.st.featurelang.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractFeatureLangValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(de.tud.st.featurelang.featureLang.FeatureLangPackage.eINSTANCE);
		return result;
	}
}
