/**
 * generated by Xtext 2.32.0
 */
package de.tud.st.featurelang.featureLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Creation Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.tud.st.featurelang.featureLang.CreationStatement#getClassElement <em>Class Element</em>}</li>
 * </ul>
 *
 * @see de.tud.st.featurelang.featureLang.FeatureLangPackage#getCreationStatement()
 * @model
 * @generated
 */
public interface CreationStatement extends Statement
{
  /**
   * Returns the value of the '<em><b>Class Element</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Class Element</em>' containment reference.
   * @see #setClassElement(de.tud.st.featurelang.featureLang.Class)
   * @see de.tud.st.featurelang.featureLang.FeatureLangPackage#getCreationStatement_ClassElement()
   * @model containment="true"
   * @generated
   */
  de.tud.st.featurelang.featureLang.Class getClassElement();

  /**
   * Sets the value of the '{@link de.tud.st.featurelang.featureLang.CreationStatement#getClassElement <em>Class Element</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Class Element</em>' containment reference.
   * @see #getClassElement()
   * @generated
   */
  void setClassElement(de.tud.st.featurelang.featureLang.Class value);

} // CreationStatement
