/**
 * generated by Xtext 2.30.0
 */
package de.tud.st.featurelang.featureLang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Inheritance Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.tud.st.featurelang.featureLang.InheritanceAction#getParent <em>Parent</em>}</li>
 * </ul>
 *
 * @see de.tud.st.featurelang.featureLang.FeatureLangPackage#getInheritanceAction()
 * @model
 * @generated
 */
public interface InheritanceAction extends EObject
{
  /**
   * Returns the value of the '<em><b>Parent</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parent</em>' containment reference.
   * @see #setParent(de.tud.st.featurelang.featureLang.Class)
   * @see de.tud.st.featurelang.featureLang.FeatureLangPackage#getInheritanceAction_Parent()
   * @model containment="true"
   * @generated
   */
  de.tud.st.featurelang.featureLang.Class getParent();

  /**
   * Sets the value of the '{@link de.tud.st.featurelang.featureLang.InheritanceAction#getParent <em>Parent</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parent</em>' containment reference.
   * @see #getParent()
   * @generated
   */
  void setParent(de.tud.st.featurelang.featureLang.Class value);

} // InheritanceAction
