/**
 * generated by Xtext 2.30.0
 */
package de.tud.st.featurelang.featureLang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Priority</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.tud.st.featurelang.featureLang.Priority#getPriority <em>Priority</em>}</li>
 * </ul>
 *
 * @see de.tud.st.featurelang.featureLang.FeatureLangPackage#getPriority()
 * @model
 * @generated
 */
public interface Priority extends EObject
{
  /**
   * Returns the value of the '<em><b>Priority</b></em>' attribute.
   * The literals are from the enumeration {@link de.tud.st.featurelang.featureLang.PriorityValue}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Priority</em>' attribute.
   * @see de.tud.st.featurelang.featureLang.PriorityValue
   * @see #setPriority(PriorityValue)
   * @see de.tud.st.featurelang.featureLang.FeatureLangPackage#getPriority_Priority()
   * @model
   * @generated
   */
  PriorityValue getPriority();

  /**
   * Sets the value of the '{@link de.tud.st.featurelang.featureLang.Priority#getPriority <em>Priority</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Priority</em>' attribute.
   * @see de.tud.st.featurelang.featureLang.PriorityValue
   * @see #getPriority()
   * @generated
   */
  void setPriority(PriorityValue value);

} // Priority
