/**
 * generated by Xtext 2.32.0
 */
package de.tud.st.featurelang.featureLang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Update Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.tud.st.featurelang.featureLang.UpdateAction#getAttribute <em>Attribute</em>}</li>
 *   <li>{@link de.tud.st.featurelang.featureLang.UpdateAction#getPriority <em>Priority</em>}</li>
 *   <li>{@link de.tud.st.featurelang.featureLang.UpdateAction#getDatatype <em>Datatype</em>}</li>
 *   <li>{@link de.tud.st.featurelang.featureLang.UpdateAction#getIdentifier <em>Identifier</em>}</li>
 *   <li>{@link de.tud.st.featurelang.featureLang.UpdateAction#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see de.tud.st.featurelang.featureLang.FeatureLangPackage#getUpdateAction()
 * @model
 * @generated
 */
public interface UpdateAction extends EObject
{
  /**
   * Returns the value of the '<em><b>Attribute</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attribute</em>' containment reference.
   * @see #setAttribute(Attribute)
   * @see de.tud.st.featurelang.featureLang.FeatureLangPackage#getUpdateAction_Attribute()
   * @model containment="true"
   * @generated
   */
  Attribute getAttribute();

  /**
   * Sets the value of the '{@link de.tud.st.featurelang.featureLang.UpdateAction#getAttribute <em>Attribute</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attribute</em>' containment reference.
   * @see #getAttribute()
   * @generated
   */
  void setAttribute(Attribute value);

  /**
   * Returns the value of the '<em><b>Priority</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Priority</em>' containment reference.
   * @see #setPriority(Priority)
   * @see de.tud.st.featurelang.featureLang.FeatureLangPackage#getUpdateAction_Priority()
   * @model containment="true"
   * @generated
   */
  Priority getPriority();

  /**
   * Sets the value of the '{@link de.tud.st.featurelang.featureLang.UpdateAction#getPriority <em>Priority</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Priority</em>' containment reference.
   * @see #getPriority()
   * @generated
   */
  void setPriority(Priority value);

  /**
   * Returns the value of the '<em><b>Datatype</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Datatype</em>' containment reference.
   * @see #setDatatype(UpdateAttributeDatatype)
   * @see de.tud.st.featurelang.featureLang.FeatureLangPackage#getUpdateAction_Datatype()
   * @model containment="true"
   * @generated
   */
  UpdateAttributeDatatype getDatatype();

  /**
   * Sets the value of the '{@link de.tud.st.featurelang.featureLang.UpdateAction#getDatatype <em>Datatype</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Datatype</em>' containment reference.
   * @see #getDatatype()
   * @generated
   */
  void setDatatype(UpdateAttributeDatatype value);

  /**
   * Returns the value of the '<em><b>Identifier</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Identifier</em>' containment reference.
   * @see #setIdentifier(UpdateAttributeIdentifier)
   * @see de.tud.st.featurelang.featureLang.FeatureLangPackage#getUpdateAction_Identifier()
   * @model containment="true"
   * @generated
   */
  UpdateAttributeIdentifier getIdentifier();

  /**
   * Sets the value of the '{@link de.tud.st.featurelang.featureLang.UpdateAction#getIdentifier <em>Identifier</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Identifier</em>' containment reference.
   * @see #getIdentifier()
   * @generated
   */
  void setIdentifier(UpdateAttributeIdentifier value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(UpdateAttributeValue)
   * @see de.tud.st.featurelang.featureLang.FeatureLangPackage#getUpdateAction_Value()
   * @model containment="true"
   * @generated
   */
  UpdateAttributeValue getValue();

  /**
   * Sets the value of the '{@link de.tud.st.featurelang.featureLang.UpdateAction#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(UpdateAttributeValue value);

} // UpdateAction
